// This file is generated by FlutterFire CLI.
// It should not be modified by hand.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeWT7XNpobZZaZ3U5ADdGgwK8aTanPKKE',
    appId: '1:480819942461:web:6695a5625f9868c5834654',
    messagingSenderId: '480819942461',
    projectId: 'studybuddy-8bfaa',
    authDomain: 'studybuddy-8bfaa.firebaseapp.com',
    storageBucket: 'studybuddy-8bfaa.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeWT7XNpobZZaZ3U5ADdGgwK8aTanPKKE',
    appId: '1:480819942461:android:6695a5625f9868c5834654',
    messagingSenderId: '480819942461',
    projectId: 'studybuddy-8bfaa',
    storageBucket: 'studybuddy-8bfaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoaxCRaIDkumzli0dFUEnt_83IUuPq1tg',
    appId: '1:480819942461:ios:d4d333b151d3fd40834654',
    messagingSenderId: '480819942461',
    projectId: 'studybuddy-8bfaa',
    storageBucket: 'studybuddy-8bfaa.firebasestorage.app',
    iosBundleId: 'com.studybuddy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoaxCRaIDkumzli0dFUEnt_83IUuPq1tg',
    appId: '1:480819942461:ios:d4d333b151d3fd40834654',
    messagingSenderId: '480819942461',
    projectId: 'studybuddy-8bfaa',
    storageBucket: 'studybuddy-8bfaa.firebasestorage.app',
    iosBundleId: 'com.studybuddy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeWT7XNpobZZaZ3U5ADdGgwK8aTanPKKE',
    appId: '1:480819942461:web:6695a5625f9868c5834654',
    messagingSenderId: '480819942461',
    projectId: 'studybuddy-8bfaa',
    authDomain: 'studybuddy-8bfaa.firebaseapp.com',
    storageBucket: 'studybuddy-8bfaa.firebasestorage.app',
  );
} 