name: Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate code
        run: |
          flutter pub run build_runner clean
          flutter pub run build_runner build --delete-conflicting-outputs
          ls -la lib/data/models/
        
      - name: Build Android APK
        run: flutter build apk --debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-debug.apk 