name: iOS Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Generate code
        run: |
          flutter pub run build_runner clean
          flutter pub run build_runner build --delete-conflicting-outputs
          
      - name: Setup iOS environment
        run: |
          cd ios
          pod install --repo-update
          
      - name: Build iOS Framework
        run: flutter build ios-framework --output=build/ios-framework
        
      - name: Upload iOS Framework
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: build/ios-framework/ 